import React, { StrictMode, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
import ArtCursor from './components/ArtCursor'
import heroVideo from '../个人网站视频背景.mp4'
import mark from '../主视觉logo.png'
import portrait from '../optimized/portrait.webp'

const artFiles = import.meta.glob('../optimized/artwork/**/*.webp', { eager: true, query: '?url', import: 'default' })
const graphicFiles = import.meta.glob('../optimized/graphic/**/*.webp', { eager: true, query: '?url', import: 'default' })
const humanize = (text) => text.replace(/\.[^.]+$/, '').replace(/,\s?(19|20)\d{2}$/, '').replace(/_/g, ' ')
const artworkStatements = {
  'Affordable Enclave': `Less than a third of the material in this sculpture comes from The Subordinate Wall, so it is a kind of cycle between works. My inspiration for this piece came from an architectural complex I passed through two years ago called Shipai Village. Located less than 2 kilometers from downtown Guangzhou, this complex was built by villagers who, because each plot of land was collectively owned and could not be bought or sold, spontaneously and haphazardly added houses, expanding outwards and upwards infinitely, constantly compressing the spacing between buildings.

In the 1990s, Guangzhou began its rapid development, and Shipai Village, due to its proximity to the city center, faced high demolition costs and was surrounded by high-rise buildings. Furthermore, due to the lack of government oversight and unified management, rents here were only about a third of those in the surrounding area, making it very affordable for migrant workers. I was fascinated by the unique shapes and state of this architectural area, so I used pure foam core cubes to represent this phenomenon—my reaction to it.`,
  'Those Happened Last Year': `My inspiration for this project starts with a question: what if all the troubles and unease happening in our world stem from the construction of basic elements?

This work is my second attempt to reinterpret reality using a geometric system. I hope to deconstruct the real events that occurred last year through this approach. The visual models of the six events are taken from iconic news images and arranged chronologically.

The reason I deconstructed these photos is to eliminate the emotional and serious nature brought by the events. Faces are usually an important component of emotion, so I blurred those faces through convolution in the photos; I also drew inspiration from Junji Ito’s manga. Among them, there are three events in which I can somehow feel a sense of participation. The Jiangyou incident was a case of bullying among minors in Sichuan, China, in July last year. After the relevant videos circulated on the internet, it immediately sparked public outrage. Later, due to the government’s stability measures and information blockade, thousands of local people took to the streets to protest. At the time, I was also in Sichuan Province and learned about the event through various methods; my sympathy for this protest is one reason I included it in the work.

Overall, I have this question: if all the complex events in the world are reduced to simple structures, is that a way to better understand them?`,
  'Goods on the shelves and memories': `This work explores the relationship between consumer culture, cultural memory, and everyday experience through the visual language of supermarket products. Drawing from my experience of living between China and Canada, I consider how familiar foods, packaging, colors, and forms become embedded in personal and familial memory.

Using the supermarket shelf as both a display structure and a symbol of consumer culture, the installation juxtaposes two visual systems: commercially packaged products purchased in Canada and hand-drawn objects associated with personal and cultural memory. The drawings, rendered in pencil on vellum and constructed to stand independently, translate familiar objects into fragile representations of recollection.

By placing commercial products and reconstructed memories within the same system of display, the work examines how cultural identity is shaped through everyday consumption, visual familiarity, and accumulated habits of seeing, tasting, and remembering.`,
  "Distance won't change its flavor": `This work explores family and cultural memory through inherited habits of cooking, seasoning, and taste. Treating everyday food practices as a form of personal archive, I consider how recipes, spices, and cooking methods carry cultural knowledge across generations and become particularly visible when living away from home.

The installation combines real spices and seasoning containers with a video depicting the gestures of Chinese cooking without actual ingredients. This deliberate absence shifts attention from food itself to the habits, movements, and memories surrounding its preparation.

A suspended cover, modeled after a household object my family used to protect food from flies, introduces the idea of preservation. Together, these elements examine how ordinary domestic practices can function as carriers of family memory and cultural continuity across distance.`
}
const artworkTitle = title => title === 'final' ? 'Goods on the shelves and memories' : title
const artworkVariant = title => { const match = title.match(/^(Affordable Enclave|The Subordinate Wall)(?: (\d+))?$/); return match ? { title:match[1], order:Number(match[2] || 1) } : { title, order:1 } }
const artworkLinks = {
  'Urban Drift Guide':{ href:'https://vimeo.com/manage/videos/1216575116', label:'Watch on Vimeo ↗' },
  'Attenuation Field':{ href:'https://www.youtube.com/watch?v=EQQmaUjrSYg', label:'Watch on YouTube ↗' }
}
const artwork = Object.values(Object.entries(artFiles).reduce((works, [path, image]) => { const [, year, name] = path.match(/artwork\\?\/(\d{4})\\?\/(.+)$/) || [], variant = artworkVariant(artworkTitle(humanize(name))), key = `${year}-${variant.title}`; works[key] ||= { year, title:variant.title, images:[], statement:artworkStatements[variant.title], link:artworkLinks[variant.title] }; works[key].images.push({ image, order:variant.order }); return works }, {})).map(work => { const images = work.images.sort((a,b) => a.order - b.order).map(({image}) => image); return { ...work, image:images[0], images } }).sort((a, b) => b.year.localeCompare(a.year) || Number(a.year === '2026' && a.title === 'Attenuation Field') - Number(b.year === '2026' && b.title === 'Attenuation Field') || a.title.localeCompare(b.title))
const graphicProjects = Object.entries(graphicFiles).reduce((projects, [sourcePath, image]) => { const path = sourcePath.replaceAll('\\', '/'); const match = path.match(/graphic\/([^/]+), (\d{4})\//); if (!match) return projects; const [, title, year] = match; const key = `${year}-${title}`; projects[key] ||= { title, year, images: [] }; projects[key].images.push({ src:image, name:path.split('/').pop().replace('.webp','') }); return projects }, {})
const footstepsOrder = ['封面1','front','book','page4','page5','page22','Frame 40 2','Frame 40 3']
const orderedGraphics = Object.values(graphicProjects).map(project => ({ ...project, images:project.images.sort((a,b) => project.title === 'When the Footsteps Become Blurred on the Initial Map' ? footstepsOrder.indexOf(a.name) - footstepsOrder.indexOf(b.name) : a.name.localeCompare(b.name)) })).sort((a,b) => b.year.localeCompare(a.year) || a.title.localeCompare(b.title))

function Link({ to, className, children }) { const go = event => { if (to.startsWith('#')) return; event.preventDefault(); window.dispatchEvent(new CustomEvent('site:navigate', { detail: to })) }; return <a href={to} className={className} onClick={go}>{children}</a> }
function Nav({ homePage = false }) { const [floating, setFloating] = useState(false), floatingRef = useRef(false), frame = useRef(0); useEffect(() => { const update = () => { if (frame.current) return; frame.current = requestAnimationFrame(() => { frame.current = 0; const next = window.scrollY > window.innerHeight * .9; if (next !== floatingRef.current) { floatingRef.current = next; setFloating(next) } }) }; update(); addEventListener('scroll', update, { passive:true }); return () => { removeEventListener('scroll', update); cancelAnimationFrame(frame.current); frame.current = 0 } }, []); return <header className={`nav ${homePage ? 'nav-home' : ''} ${floating ? 'nav-floating' : ''}`}><Link to="/" className="home-logo" aria-label="Home"><img src={mark} alt=""/></Link><nav><Link to="/artwork">Artwork</Link><Link to="/cv">CV</Link><Link to="/statement">Statement</Link><Link to="/graphic-project">Graphic Project</Link><a href="/#contact">Contact me</a></nav></header> }
function PageShell({ children, name }) { return <><Nav /><main className={`page ${name}`}>{children}</main></> }
function YearRail({ years, prefix, label }) { const [active, setActive] = useState(years[0]), key = years.join('|'), dragging = useRef(false); useEffect(() => { document.documentElement.classList.add('has-year-rail'); return () => document.documentElement.classList.remove('has-year-rail') }, []); useEffect(() => { let frame = 0; const update = () => { if (frame) return; frame = requestAnimationFrame(() => { frame = 0; const current = years.map(year => ({ year, node:document.getElementById(`${prefix}-${year}`) })).filter(({node}) => node).map(({year,node}) => ({ year, distance:Math.abs(node.getBoundingClientRect().top - innerHeight * .38) })).sort((a,b) => a.distance - b.distance)[0]; if (current) setActive(current.year) }) }; update(); addEventListener('scroll', update, { passive:true }); addEventListener('resize', update); return () => { removeEventListener('scroll', update); removeEventListener('resize', update); cancelAnimationFrame(frame) } }, [key, prefix]); const go = year => { setActive(year); document.getElementById(`${prefix}-${year}`)?.scrollIntoView({ behavior:'smooth', block:'start' }) }, drag = event => { const bounds = event.currentTarget.getBoundingClientRect(), progress = Math.max(0, Math.min(1, (event.clientY - bounds.top) / bounds.height)), distance = document.documentElement.scrollHeight - innerHeight; scrollTo({ top:progress * distance, behavior:'auto' }) }, startDrag = event => { if (event.target.closest('button')) return; dragging.current = true; event.currentTarget.setPointerCapture(event.pointerId); drag(event) }, moveDrag = event => { if (dragging.current) drag(event) }, endDrag = () => { dragging.current = false }; return <aside className="year-rail" aria-label={`${label} year navigation`}><div className="year-rail__track" onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}>{years.map(year => <button className={active === year ? 'is-active' : ''} key={year} onClick={() => go(year)} aria-current={active === year ? 'true' : undefined}>{year}</button>)}</div></aside> }
const scrollStatements = ['Making is becoming effortless.','Possibilities can be infinite.','But possibility is not purpose.','When everything can be made,','What is worth making?','Nothing is impossible.','Not everything is necessary.']
function TypewriterLine({ text, active }) { const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches, [count, setCount] = useState(reduced ? text.length : 0), frame = useRef(0), started = useRef(reduced), completed = useRef(reduced); useEffect(() => { if (!active) { cancelAnimationFrame(frame.current); if (!completed.current) { started.current = false; setCount(0) } return } if (started.current) return; started.current = true; setCount(0); let start = 0; const duration = Math.min(820, Math.max(520, text.length * 22)); const type = time => { start ||= time; const next = Math.min(text.length, Math.floor((time - start) / duration * (text.length + 1))); setCount(next); if (next < text.length) frame.current = requestAnimationFrame(type); else completed.current = true }; frame.current = requestAnimationFrame(type); return () => { cancelAnimationFrame(frame.current); if (!completed.current) started.current = false } }, [active, text]); return <><span aria-hidden="true">{text.slice(0, count)}</span>{active && count < text.length && <i className="type-caret" aria-hidden="true"/>}<span className="sr-only">{text}</span></> }
function PoemTypewriter({ active, animationLock }) { const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches, [counts, setCounts] = useState(() => scrollStatements.map(text => reduced ? text.length : 0)), timer = useRef(0), started = useRef(reduced), completed = useRef(reduced); useEffect(() => { if (!active) { if (!completed.current) { clearTimeout(timer.current); started.current = false; animationLock.current = false; setCounts(scrollStatements.map(() => 0)) } return } if (started.current) return; started.current = true; animationLock.current = true; let line = 0, character = 0; const tick = () => { const text = scrollStatements[line]; character += 1; setCounts(previous => previous.map((count, index) => index === line ? Math.min(character, text.length) : count)); if (character < text.length) timer.current = window.setTimeout(tick, 18); else if (line < scrollStatements.length - 1) { line += 1; character = 0; timer.current = window.setTimeout(tick, 120) } else { completed.current = true; animationLock.current = false } }; timer.current = window.setTimeout(tick, 180); return () => { clearTimeout(timer.current); if (!completed.current) { started.current = false; animationLock.current = false } } }, [active, animationLock]); return scrollStatements.map((text, index) => <p key={text}><span className="poem-line-ghost" aria-hidden="true">{text}</span><span className="poem-line-typed" aria-hidden="true">{text.slice(0, counts[index])}{active && counts[index] > 0 && counts[index] < text.length && <i className="type-caret"/>}</span><span className="sr-only">{text}</span></p>) }
function ScrollTypography() { const section = useRef(null), [progress, setProgress] = useState(0), [inView, setInView] = useState(false), inViewRef = useRef(false), frame = useRef(0), target = useRef(0), current = useRef(0), wheelLock = useRef(0), poemAnimationLock = useRef(false); useEffect(() => { const animate = () => { const gap = target.current - current.current; current.current = Math.abs(gap) < .0002 ? target.current : current.current + gap * .14; setProgress(current.current); frame.current = current.current === target.current ? 0 : requestAnimationFrame(animate) }; const update = () => { const node = section.current; if (!node) return; const rect = node.getBoundingClientRect(), distance = node.offsetHeight - innerHeight, visible = rect.top <= 2 && rect.bottom >= 2; target.current = Math.max(0, Math.min(1, -rect.top / distance)); if (visible !== inViewRef.current) { inViewRef.current = visible; setInView(visible) }; if (!frame.current) frame.current = requestAnimationFrame(animate) }; const snap = event => { const node = section.current; if (!node || matchMedia('(prefers-reduced-motion: reduce)').matches || Math.abs(event.deltaY) < 8) return; const rect = node.getBoundingClientRect(); if (rect.top > 1 || rect.bottom < 2) return; const index = Math.round(Math.max(0, Math.min(1, -rect.top / (node.offsetHeight - innerHeight)))), direction = event.deltaY > 0 ? 1 : -1, next = Math.max(0, Math.min(1, index + direction)); if (index === 1 && direction > 0 && poemAnimationLock.current) { event.preventDefault(); return } if (next === index) return; event.preventDefault(); if (wheelLock.current) return; wheelLock.current = window.setTimeout(() => { wheelLock.current = 0 }, 900); scrollTo({ top:node.offsetTop + next * (node.offsetHeight - innerHeight), behavior:'smooth' }) }; update(); addEventListener('scroll', update, { passive:true }); addEventListener('resize', update); addEventListener('wheel', snap, { passive:false }); return () => { removeEventListener('scroll', update); removeEventListener('resize', update); removeEventListener('wheel', snap); cancelAnimationFrame(frame.current); clearTimeout(wheelLock.current); frame.current = 0; wheelLock.current = 0; poemAnimationLock.current = false } }, []); const rawBlend = Math.max(0, Math.min(1, (progress - .34) / .32)), blend = rawBlend * rawBlend * (3 - 2 * rawBlend); return <section className="scroll-typography scroll-typography--poem" ref={section} aria-label="Artist manifesto"><div className="scroll-typography__sticky"><p className="manifesto-type" style={{ opacity:1 - blend, transform:`translate3d(0, ${-blend * 18}px, 0) scale(${1 - blend * .02})` }}><TypewriterLine text="Nothing is impossible." active={inView && progress < .45}/></p><div className="manifesto-poem" style={{ opacity:blend, transform:`translate3d(0, ${(1 - blend) * 18}px, 0)` }}><PoemTypewriter active={inView && progress > .52} animationLock={poemAnimationLock}/></div></div></section> }
function Home() { const [videoReady, setVideoReady] = useState(false); useEffect(() => { const timer = setTimeout(() => setVideoReady(true), 600); return () => clearTimeout(timer) }, []); return <><Nav homePage/><main className="home-page"><video autoPlay loop muted playsInline preload="none" poster={mark}>{videoReady && <source src={heroVideo} type="video/mp4" />}</video><div className="home-wash"/><div className="home-bottom-fade" aria-hidden="true"/><Link className="home-enter" to="/artwork">ENTER <span>↓</span></Link></main><ScrollTypography/><Contact /></> }
function Artwork() { const [active, setActive] = useState(null); const grouped = useMemo(() => [...new Set(artwork.map(({ year }) => year))].map(year => [year, artwork.filter(work => work.year === year)]), []); return <PageShell name="artwork-page"><div className="page-top"><p>Artwork</p><span>2026—2019</span></div><YearRail years={grouped.map(([year]) => year)} prefix="artwork" label="Artwork"/>{grouped.map(([year, works]) => <section className="year-section" id={`artwork-${year}`} key={year}><h1>{year}</h1><div className="works-grid">{works.map((work, i) => <button className={`work work-${i % 7}`} key={work.title} onClick={() => setActive(work)}><img src={work.image} alt={work.title} loading="lazy" decoding="async"/><span>{work.title}</span></button>)}</div></section>)}<WorkDialog work={active} close={() => setActive(null)}/></PageShell> }
function WorkDialog({ work, close }) { const [index, setIndex] = useState(0), images = work?.images || []; const previous = () => setIndex(current => images.length ? (current - 1 + images.length) % images.length : 0), next = () => setIndex(current => images.length ? (current + 1) % images.length : 0); useEffect(() => setIndex(0), [work]); useEffect(() => { const onKey = e => { if (e.key === 'Escape') close(); if (e.key === 'ArrowLeft') previous(); if (e.key === 'ArrowRight') next() }; addEventListener('keydown', onKey); return () => removeEventListener('keydown', onKey) }, [close, images.length]); if (!work) return null; return <div className="overlay" onClick={close} role="dialog" aria-modal="true" aria-label={work.title}><article className="work-view" onClick={e => e.stopPropagation()}><button className="dialog-close" onClick={close}>Close ×</button><figure className="work-view__media"><img src={images[index]} alt={`${work.title} — image ${index + 1}`}/>{images.length > 1 && <><button className="work-view__arrow work-view__arrow--previous" onClick={previous} aria-label="Previous image">←</button><button className="work-view__arrow work-view__arrow--next" onClick={next} aria-label="Next image">→</button><figcaption>{String(index + 1).padStart(2,'0')} / {String(images.length).padStart(2,'0')}</figcaption></>}</figure><div className="work-view__meta"><p>{work.year}</p><h2>{work.title}</h2><p>Artwork · {work.year}</p></div>{work.statement && <div className="work-view__statement">{work.statement.split('\n\n').map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div>}{work.link && <a className="work-view__link" href={work.link.href} target="_blank" rel="noreferrer">{work.link.label}</a>}</article></div> }
const cv = [['Education',[['2022—2027','Kwantlen Polytechnic University, Surrey BC — BFA'],['2025','Google UX Design, Online — Certificate']]],['Selected Exhibitions',[['2026','This ’n’ That (Group), Kwantlen Polytechnic University, Surrey BC'],['2025','Mining Your Archive (Group), Kwantlen Polytechnic University, Surrey BC'],['2025','Don’t Quit Your Day Job (Group), Kwantlen Polytechnic University, Surrey BC']]],['Professional Experience',[['2026','UX Designer, Senaura Art — Full-time internship, July—August'],['2026','Graphic Designer, BrandD — Full-time internship, March—June'],['2025','Photographer, SCNU — Full-time internship, June—August'],['2025','Graphic Design & Video Editing, Xing Qu Dao — Full-time internship, April—June']]],['Volunteer Experience',[['2018','Art Teacher and Assistant, Chiang Rai, Thailand']]],['Selected Awards',[['2025','FA International Frontier Innovation Design Competition — Gold Medal'],['2026 / 2025','The Dean’s Honour Roll, Kwantlen Polytechnic University'],['2020','The Duke of Edinburgh’s International Silver Award']]]]
function CV() { return <PageShell name="text-page"><div className="text-heading"><p>Curriculum Vitae</p><h1>Ruokun Ma<br/><i>(Neil)</i></h1><span>Visual Artist & Graphic Designer<br/>Surrey, BC / Guangzhou, CN</span></div><div className="cv-list">{cv.map(([label, rows]) => <section key={label}><h2>{label}</h2>{rows.map(([date, text]) => <p key={date+text}><span>{date}</span>{text}</p>)}</section>)}</div></PageShell> }
function Statement() { return <PageShell name="statement-page"><div className="statement-photo"><img src={portrait} alt="Ruokun Ma"/></div><article><p className="label">Artist Statement</p><h1>Ruokun Ma<br/><i>(Neil)</i></h1><p>Ruokun Ma (Neil) is a Chinese-born visual arts practitioner whose work explores the relationships between consumer culture, identity, and spatial experience through institutional visual language. Born in Tianjin and raised in Guangzhou, his practice reconstructs urban and social conditions through processes of abstraction, translation, and systemization, often examining how seemingly ordinary experiences are shaped by larger systems.</p><p><i>Affordable Enclave</i> responds to Shipai Village in Guangzhou, an urban village shaped by informal construction and limited land ownership. Surrounded by high-rise developments, its low rents make it an important living space for migrant workers while positioning it at the margins of the urban economy.</p><p>I reconstructed this compressed environment using uniform foam core cubes, with less than a third of the material reused from a previous work. By reducing the village to modular units, the work emphasizes repetition, density, and spatial tension, reflecting on how affordable spaces and labor are standardized within urban development and consumer culture.</p><p><i>Urban Drift Guide</i> extends this interest to everyday movement, examining how urban exploration is shaped by recommendation systems, commercial spaces, and predetermined routes. Taking the form of a conventional travel guide, the project examines how recommendation systems, commercial infrastructures, and algorithmic navigation increasingly organize the experience of wandering.</p><p>Across these works, Ma considers how urban environments and everyday experiences are structured, standardized, and mediated by economic and institutional systems, questioning where autonomy remains within spaces that appear to offer freedom and choice.</p></article></PageShell> }
function Graphic() { const [active, setActive] = useState(null), years = useMemo(() => [...new Set(orderedGraphics.map(({year}) => year))], []); return <PageShell name="graphic-page"><div className="page-top"><p>Graphic Project</p><span>Selected Works</span></div><YearRail years={years} prefix="graphic" label="Graphic"/>{orderedGraphics.map((item, index) => <section className={`graphic-project ${item.title === 'When the Footsteps Become Blurred on the Initial Map' ? 'footsteps-project' : ''}`} id={orderedGraphics.findIndex(project => project.year === item.year) === index ? `graphic-${item.year}` : undefined} key={item.title}><header><span>0{index + 1}</span><h1>{item.title} <small>{item.year}</small></h1></header><div>{item.images.map(({src,name}, i) => <button className="graphic-image" key={src} onClick={() => setActive({ ...item, index:i })} aria-label={`View ${item.title}, image ${i + 1}`}><img src={src} alt={`${item.title} — ${name || i+1}`} loading="lazy" decoding="async" /></button>)}</div></section>)}<GraphicDialog project={active} close={() => setActive(null)}/></PageShell> }
function GraphicDialog({ project, close }) { const [index, setIndex] = useState(0), images = project?.images || []; useEffect(() => setIndex(project?.index || 0), [project]); const previous = () => setIndex(current => images.length ? (current - 1 + images.length) % images.length : 0), next = () => setIndex(current => images.length ? (current + 1) % images.length : 0); useEffect(() => { const onKey = event => { if (event.key === 'Escape') close(); if (event.key === 'ArrowLeft') previous(); if (event.key === 'ArrowRight') next() }; addEventListener('keydown', onKey); return () => removeEventListener('keydown', onKey) }, [close, images.length]); if (!project) return null; return <div className="overlay graphic-overlay" onClick={close} role="dialog" aria-modal="true" aria-label={project.title}><article className="work-view graphic-view" onClick={event => event.stopPropagation()}><button className="dialog-close" onClick={close}>Close ×</button><figure className="work-view__media"><img src={images[index].src} alt={`${project.title} — image ${index + 1}`}/>{images.length > 1 && <><button className="work-view__arrow work-view__arrow--previous" onClick={previous} aria-label="Previous image">←</button><button className="work-view__arrow work-view__arrow--next" onClick={next} aria-label="Next image">→</button><figcaption>{String(index + 1).padStart(2,'0')} / {String(images.length).padStart(2,'0')}</figcaption></>}</figure><div className="work-view__meta"><p>{project.year}</p><h2>{project.title}</h2><p>Graphic Project · {project.year}</p></div></article></div> }
function Contact() { return <section id="contact" className="contact"><h2>RUOKUN MA</h2><div className="contact-socials"><a href="https://www.instagram.com/neilmrk89/" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg></a><a href="https://www.behance.net/neilmark1" target="_blank" rel="noreferrer" aria-label="Behance"><svg className="behance-icon" viewBox="0 0 24 24" aria-hidden="true"><text x="1" y="17">Bē</text></svg></a><a href="https://www.linkedin.com/in/ruokun-ma-46539a222" target="_blank" rel="noreferrer" aria-label="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 10v7M8 7v.01M12 17v-4.1c0-1.8 2.8-2 2.8 0V17M12 10v7"/></svg></a><a href="mailto:neilmrk666@gmail.com" aria-label="Email Ruokun Ma"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="1.5"/><path d="m4 7 8 6 8-6"/></svg></a></div><p>ALL RIGHTS RESERVED © 2026</p></section> }
function RouteTransition({ intro = false }) { return <div className="route-transition" aria-hidden="true"><div className="route-transition__content"><img src={mark} alt=""/>{intro && <p className="route-transition__intro">Nothing is impossible.</p>}</div></div> }
function App() { const [path, setPath] = useState(location.pathname.replace(/\/$/, '') || '/'), [transitioning, setTransitioning] = useState(true), [intro, setIntro] = useState(true), timers = useRef([]), pathRef = useRef(path); useEffect(() => { pathRef.current = path }, [path]); useEffect(() => { const clearTimers = () => { timers.current.forEach(clearTimeout); timers.current = [] }; timers.current.push(setTimeout(() => { setTransitioning(false); setIntro(false); timers.current = [] }, 2400)); const show = (nextPath, push = true) => { if (nextPath === pathRef.current) return; clearTimers(); setIntro(false); setTransitioning(true); timers.current.push(setTimeout(() => { if (push) history.pushState({}, '', nextPath); pathRef.current = nextPath; setPath(nextPath); scrollTo(0, 0) }, 940)); timers.current.push(setTimeout(() => { setTransitioning(false); timers.current = [] }, 2400)) }; const move = ({ detail }) => show(detail); const back = () => show(location.pathname.replace(/\/$/, '') || '/', false); addEventListener('site:navigate', move); addEventListener('popstate', back); return () => { removeEventListener('site:navigate', move); removeEventListener('popstate', back); clearTimers() } }, []); let view = <Home />; if (path === '/artwork') view = <Artwork />; if (path === '/cv') view = <CV />; if (path === '/statement') view = <Statement />; if (path === '/graphic-project') view = <Graphic />; return <><ArtCursor/>{view}{transitioning && <RouteTransition intro={intro}/>}</> }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
