import React, { StrictMode, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
import ArtCursor from './components/ArtCursor'
import ScrollVelocity from './components/ScrollVelocity'
import heroVideo from '../个人网站视频背景.mp4'
import mark from '../主视觉logo.png'
import portrait from '../optimized/portrait.webp'

const artFiles = import.meta.glob('../optimized/artwork/**/*.webp', { eager: true, query: '?url', import: 'default' })
const graphicFiles = import.meta.glob('../optimized/graphic/**/*.webp', { eager: true, query: '?url', import: 'default' })
const humanize = (text) => text.replace(/\.[^.]+$/, '').replace(/,\s?(19|20)\d{2}$/, '').replace(/_/g, ' ')
const artwork = Object.entries(artFiles).map(([path, image]) => { const [, year, name] = path.match(/artwork\\?\/(\d{4})\\?\/(.+)$/) || []; return { year, title: humanize(name), image } }).sort((a, b) => b.year.localeCompare(a.year) || a.title.localeCompare(b.title))
const graphicProjects = Object.entries(graphicFiles).reduce((projects, [sourcePath, image]) => { const path = sourcePath.replaceAll('\\', '/'); const match = path.match(/graphic\/([^/]+), (\d{4})\//); if (!match) return projects; const [, title, year] = match; const key = `${year}-${title}`; projects[key] ||= { title, year, images: [] }; projects[key].images.push(image); return projects }, {})
const orderedGraphics = Object.values(graphicProjects).sort((a,b) => b.year.localeCompare(a.year) || a.title.localeCompare(b.title))

function Link({ to, className, children }) { const go = event => { if (to.startsWith('#')) return; event.preventDefault(); window.dispatchEvent(new CustomEvent('site:navigate', { detail: to })) }; return <a href={to} className={className} onClick={go}>{children}</a> }
function Nav() { const [floating, setFloating] = useState(false), floatingRef = useRef(false), frame = useRef(0); useEffect(() => { const update = () => { if (frame.current) return; frame.current = requestAnimationFrame(() => { frame.current = 0; const next = window.scrollY > window.innerHeight * .9; if (next !== floatingRef.current) { floatingRef.current = next; setFloating(next) } }) }; update(); addEventListener('scroll', update, { passive:true }); return () => { removeEventListener('scroll', update); cancelAnimationFrame(frame.current) } }, []); return <header className={`nav ${floating ? 'nav-floating' : ''}`}><Link to="/" className="home">Home</Link><nav><Link to="/artwork">Artwork</Link><Link to="/cv">CV</Link><Link to="/statement">Statement</Link><Link to="/graphic-project">Graphic Project</Link><a href="/#contact">Contact me</a></nav></header> }
function PageShell({ children, name }) { return <><Nav /><main className={`page ${name}`}>{children}</main></> }
function Home() { const [videoReady, setVideoReady] = useState(false); useEffect(() => { const timer = setTimeout(() => setVideoReady(true), 600); return () => clearTimeout(timer) }, []); return <><Nav /><main className="home-page"><video autoPlay loop muted playsInline preload="none" poster={mark}>{videoReady && <source src={heroVideo} type="video/mp4" />}</video><div className="home-wash"/><img src={mark} className="home-mark" alt="Ruokun Ma"/><p className="home-credit">RUOKUN MA (NEIL)<br/>VISUAL ARTIST & GRAPHIC DESIGNER</p><Link className="home-enter" to="/artwork">ENTER <span>↓</span></Link></main><ScrollVelocity/><Contact /></> }
function Artwork() { const [active, setActive] = useState(null); const grouped = useMemo(() => [...new Set(artwork.map(({ year }) => year))].map(year => [year, artwork.filter(work => work.year === year)]), []); return <PageShell name="artwork-page"><div className="page-top"><p>Artwork</p><span>2026—2019</span></div>{grouped.map(([year, works]) => <section className="year-section" key={year}><h1>{year}</h1><div className="works-grid">{works.map((work, i) => <button className={`work work-${i % 7}`} key={work.title} onClick={() => setActive(work)}><img src={work.image} alt={work.title} loading="lazy" decoding="async"/><span>{work.title}</span></button>)}</div></section>)}<WorkDialog work={active} close={() => setActive(null)}/></PageShell> }
function WorkDialog({ work, close }) { useEffect(() => { const onKey = e => e.key === 'Escape' && close(); addEventListener('keydown', onKey); return () => removeEventListener('keydown', onKey) }, [close]); if (!work) return null; return <div className="overlay" onClick={close}><article className="work-view" onClick={e => e.stopPropagation()}><button onClick={close}>Close ×</button><img src={work.image} alt={work.title}/><div><p>{work.year}</p><h2>{work.title}</h2><p>Artwork · {work.year}</p></div></article></div> }
const cv = [['Education',[['2022—2027','Kwantlen Polytechnic University, Surrey BC — BFA'],['2025','Google UX Design, Online — Certificate']]],['Selected Exhibitions',[['2026','This ’n’ That (Group), Kwantlen Polytechnic University, Surrey BC'],['2025','Mining Your Archive (Group), Kwantlen Polytechnic University, Surrey BC'],['2025','Don’t Quit Your Day Job (Group), Kwantlen Polytechnic University, Surrey BC']]],['Professional Experience',[['2026','UX Designer, Senaura Art — Full-time internship, July—August'],['2026','Graphic Designer, BrandD — Full-time internship, March—June'],['2025','Photographer, SCNU — Full-time internship, June—August'],['2025','Graphic Design & Video Editing, Xing Qu Dao — Full-time internship, April—June']]],['Volunteer Experience',[['2018','Art Teacher and Assistant, Chiang Rai, Thailand']]],['Selected Awards',[['2025','FA International Frontier Innovation Design Competition — Gold Medal'],['2026 / 2025','The Dean’s Honour Roll, Kwantlen Polytechnic University'],['2020','The Duke of Edinburgh’s International Silver Award']]]]
function CV() { return <PageShell name="text-page"><div className="text-heading"><p>Curriculum Vitae</p><h1>Ruokun Ma<br/><i>(Neil)</i></h1><span>Visual Artist & Graphic Designer<br/>Surrey, BC / Guangzhou, CN</span></div><div className="cv-list">{cv.map(([label, rows]) => <section key={label}><h2>{label}</h2>{rows.map(([date, text]) => <p key={date+text}><span>{date}</span>{text}</p>)}</section>)}</div></PageShell> }
function Statement() { return <PageShell name="statement-page"><div className="statement-photo"><img src={portrait} alt="Ruokun Ma"/></div><article><p className="label">Artist Statement</p><h1>Ruokun Ma<br/><i>(Neil)</i></h1><p>Ruokun Ma (Neil) is a Chinese-born visual arts practitioner whose work explores the relationships between consumer culture, identity, and spatial experience through institutional visual language. Born in Tianjin and raised in Guangzhou, his practice reconstructs urban and social conditions through processes of abstraction, translation, and systemization, often examining how seemingly ordinary experiences are shaped by larger systems.</p><p><i>Affordable Enclave</i> responds to Shipai Village in Guangzhou, an urban village shaped by informal construction and limited land ownership. Surrounded by high-rise developments, its low rents make it an important living space for migrant workers while positioning it at the margins of the urban economy.</p><p>I reconstructed this compressed environment using uniform foam core cubes, with less than a third of the material reused from a previous work. By reducing the village to modular units, the work emphasizes repetition, density, and spatial tension, reflecting on how affordable spaces and labor are standardized within urban development and consumer culture.</p><p><i>Urban Drift Guide</i> extends this interest to everyday movement, examining how urban exploration is shaped by recommendation systems, commercial spaces, and predetermined routes. Taking the form of a conventional travel guide, the project examines how recommendation systems, commercial infrastructures, and algorithmic navigation increasingly organize the experience of wandering.</p><p>Across these works, Ma considers how urban environments and everyday experiences are structured, standardized, and mediated by economic and institutional systems, questioning where autonomy remains within spaces that appear to offer freedom and choice.</p></article></PageShell> }
function Graphic() { return <PageShell name="graphic-page"><div className="page-top"><p>Graphic Project</p><span>Selected Works</span></div>{orderedGraphics.map((item, index) => <section className="graphic-project" key={item.title}><header><span>0{index + 1}</span><h1>{item.title} <small>{item.year}</small></h1></header><div>{item.images.map((image, i) => <img src={image} key={image} alt={`${item.title} — ${i+1}`} loading="lazy" decoding="async" />)}</div></section>)}</PageShell> }
function Contact() { return <section id="contact" className="contact"><p>Contact me</p><a href="mailto:neilmrk666@gmail.com">neilmrk666@gmail.com</a><footer><span>© 2026 RUOKUN MA</span><span>VISUAL ARTIST / GRAPHIC DESIGNER</span><Link to="/">BACK TO TOP ↑</Link></footer></section> }
function App() { const [path, setPath] = useState(location.pathname.replace(/\/$/, '') || '/'); useEffect(() => { const move = ({ detail }) => { const update = () => { history.pushState({}, '', detail); setPath(detail) }; document.startViewTransition ? document.startViewTransition(update) : update() }; const back = () => setPath(location.pathname.replace(/\/$/, '') || '/'); addEventListener('site:navigate', move); addEventListener('popstate', back); return () => { removeEventListener('site:navigate', move); removeEventListener('popstate', back) } }, []); let view = <Home />; if (path === '/artwork') view = <Artwork />; if (path === '/cv') view = <CV />; if (path === '/statement') view = <Statement />; if (path === '/graphic-project') view = <Graphic />; return <><ArtCursor/>{view}</> }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
